name: upray_mobile
description: "Upray"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_flavorizr: ^2.2.3
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  auto_route: ^8.1.3
  get_it: ^7.7.0
  provider: ^6.1.2
  dartz: ^0.10.1
  slang: ^3.30.2
  dio: ^5.4.3+1
  fimber: ^0.7.0
  talker_logger: ^4.2.0
  talker_dio_logger: ^4.2.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  talker_bloc_logger: ^4.2.0
  slang_flutter: ^3.30.0
  slang_build_runner: ^3.30.0
  intl: ^0.18.1
  credit_card_validator: ^2.1.0
  mask_text_input_formatter: ^2.9.0
  mockito: ^5.4.4
  bloc_test: ^9.1.7
  mocktail: ^1.0.3
  equatable: ^2.0.5
  solid_lints: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
