name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3.6
        with:
          channel: stable
          version: 3.19.6

      - name: Install dependencies
        run: flutter pub get

      - name: Run runner
        run: dart run build_runner build

      - name: Analyze project source
        run: dart analyze
#
#      - name: Run tests
#        run: flutter test